# Generated by Django 5.0.7 on 2024-07-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_order_orderproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
